/*
 * Autogenerated by the Meson build system.
 * Do not edit, your changes will be lost.
 */

#pragma once

#define DATADIR "/usr/local/share"

#define GETTEXT_PACKAGE "msitools"

#define LOCALEDIR "/usr/local/share/locale"

#define PACKAGE_BUGREPORT "https://gitlab.gnome.org/GNOME/msitools/issues"

#define PACKAGE_NAME "msitools"

#define PACKAGE_STRING "msitools UNKNOWN"

#define PACKAGE_VERSION "UNKNOWN"

